# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "afb0608c347be4e5e306021d46c07096"
name = "wishlis-test1"
handle = "wishlis-test1"
application_url = "https://productivity-naked-resume-lightbox.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3749937e.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://productivity-naked-resume-lightbox.trycloudflare.com/auth/callback",
  "https://productivity-naked-resume-lightbox.trycloudflare.com/auth/shopify/callback",
  "https://productivity-naked-resume-lightbox.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
